### ISSUE TITLE
图片+ 文字 如何对齐（2020-02-20）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#101]
### 文字 + 图片对齐
> 对于这个需求，我之前采取的措施都是 display 布局。突然flex布局对某些效果有限制了，我哭了。。
- 发现了其实原生css 有这个操作

> 图片元素
```css 
vertical-align:sub;  // 属性有很多实在对齐，自己选用
```

**Comment by yaogengzhu** [comment]
### 补充一个css 文字两端对齐，兼容iOS端
```scss
@mixin justify_and_ios($top: 0) {
    position: relative;
    top: $top;
    display: inline-block;
    height: 100%;
    width: 100%;
    text-align: justify;
    vertical-align: top;
    &::after {
        display: inline-block;
        width: 100%;
        content: '';
        height: 0;
    }
}

.text-aligin {
    @include justify_and_ios()
}
```
