### ISSUE TITLE
clip-path 切割图形（2020-05-07）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#105]
## clip-path 切割图形
>  需求是切图一个不规则的图形，方案原本采用伪元素处理，更好的方案处理是使用css: cli-path处理。
![image](https://user-images.githubusercontent.com/42566669/81251503-02654580-9056-11ea-9624-deb93c5c9fce.png)
- 以下采用的css-in-jss
```css
 mermberBg: {
        position: 'absolute',
        minWidth: '52px',
        height: '20px',
        right: 0,
        top: 0,
        '-webkit-clip-path': 'polygon(0 0, 100% 0, 78% 100%, 0 100%)',
    }
```
