### ISSUE TITLE
css 处理文字两边自适应（iOS 兼容）（2020-05-27）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#110]
##  css 处理文字两边自适应（iOS 兼容）
```css
@mixin justify_and_ios($top: 0) {
    position: relative;
    top: $top;
    display: inline-block;
    height: 100%;
    width: 100%;
    text-align: justify;
    vertical-align: top;
    &::after {
        display: inline-block;
        width: 100%;
        content: '';
        height: 0;
    }
}

.text-aligin {
    @include justify_and_ios()
}

```
