### ISSUE TITLE
解决一些滚动穿透！你要知道的`touch-action: none;`  (2020-06-02)

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#112]
### 解决一些滚动穿透！你要知道的`touch-action: none;` 
> 在开发小程序时，弹框下的内容一起滚动，影响一些体验，发现css 一个属性可以很好的解决这个问题。

- 在弹框的最外层盒子上添加一个css属性

```css
.order-track_box {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(0,0,0,0.5);
            touch-action: none;
}
```
