### ISSUE TITLE
关闭微信浏览器下拉“网页由xxx提供，QQ浏览器内核" （2020-07-10）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#113]
## 关闭微信浏览器下拉“网页由xxx提供，QQ浏览器内核"
> 需求背景： 在vue项目中，我们提供一个下载页面。多个页面，使用到了 `vue-plain-slider`。但是在微信端和微信浏览器的下拉事件产生了冲突，这时我们不得不关闭这个事件

- 解决代码
```css
html,body,#app,.wx-pages{
    padding: 0;
    margin: 0;
    height: 100%;
    overflow: hidden;
    -webkit-overflow-scrolling: touch;
}
```
- 在项目的public/index.html 文件中加入事件
```js
document.body.addEventListener('touchmove', function(e) {
     e.preventDefault(); 
}, {
     passive: false
})
```
