### ISSUE TITLE
60行代码撸一个自定义密码输入框（2020-7-1）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#133]
![input](https://user-images.githubusercontent.com/42566669/124097044-bfea9d80-da8d-11eb-8bba-9bbae77791ea.gif)

## 效果代码
```js
import React from 'react'
import SimulateInput from './component/SimulateInput/SimulateInput'

const App = () => {
    return (
        <div>
            <h1>请输入8位工号</h1>
            <SimulateInput onConfirm={() => {}} />
            <h1>请输入6位工号</h1>
            <SimulateInput length={6} onConfirm={() => {}} />
            <h1>请输入6位数密码</h1>
            <SimulateInput length={6} type="password" onConfirm={() => {}} />
        </div>
    )
}
export default App
```

## 实现js代码
```js
import React, { useCallback, useEffect, useMemo, useState } from 'react'
import PropTypes from 'prop-types'
import './SimulateInput.css'
const SimulateInput = (props) => {
    const [text, setText] = useState('')
    const [focus, setFocus] = useState(false)
    const onInputChange = (e) => {
        const value = e.target.value
            .replace(/[^0-9]$/g, '')
            .slice(0, props.length)
        setText(value)
    }
    useEffect(() => {
        if (text.length === props.length) {
            props.onConfirm()
        }
    }, [text])
    function getValue(type) {
        return text.slice(type.length - 1, type)
    }
    return (
        <div className="box">
            {Array.from({ length: props.length })
                .fill('')
                .map((item, index) => {
                    return (
                        <div
                            key={index}
                            className={[
                                'item',
                                text.length === index && focus && 'active',
                            ].join(' ')}
                        >
                            {props.type === 'text' &&
                                text.slice(index, index + 1)}
                            {props.type === 'password' &&
                                text.length > index && <span className='password'></span>}
                        </div>
                    )
                })}
            <input
                type="text"
                value={text}
                className="input"
                onFocus={() => setFocus(true)}
                onBlur={() => setFocus(false)}
                onChange={onInputChange}
            />
        </div>
    )
}
SimulateInput.propTypes = {
    length: PropTypes.number,
    type: PropTypes.string,
    onConfirm: PropTypes.func
}
SimulateInput.defaultProps = {
    length: 8,
    type: 'text',
    onConfirm: () => {}
}
export default SimulateInput
```

## 实现css代码
```css
.box {
    position: relative;
    width: 100%;
    height: 100px;
    display: flex;
    align-items: center;
    justify-content: space-around;
  }
  
  .item {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 40px;
    height: 40px;
    border-radius: 5px;
    border: 1px solid #ddd;
    font-size: 20px;
    color: #000;
    font-weight: bold;
  }
  
  .active {
    border: 1px solid green;
  }
  .active::after {
    position: absolute;
    content: "";
    width: 2px;
    height: 28px;
    background-color: green;
    opacity: 0;
    animation: myfirst 1s infinite;
  }

  .password {
      display: flex;
      align-items: center;
      width: 10px;
      height: 10px;
      background-color: #000;
      border-radius: 50%;
  }
  
  .input {
    position: absolute;
    width: 100%;
    height: 50px;
    opacity: 0;
  }
  
  @keyframes myfirst {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  
```
