### ISSUE TITLE
监听滚动事件失效（2022-3-19）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#156]
**window监听scroll事件失效，window.addEventListener(‘scroll‘,callback)**

[参考文章](https://blog.csdn.net/qq_41442929/article/details/110882093)

```html
  <div class="wrapper">
    <div class="container">
    	...
    	...
    	...
    </div>
    <div class="content"></div>
  </div>

```

```css
.wrapper{
	height:100%;
	overflow:scroll;
	/*其他样式*/
}
```
```js
const wrapper = document.getElementsByClassName('wrapper')[0]
wrapper.addEventListener('scroll',(event) => console.log(event))

```
