### ISSUE TITLE
自定义组件适配 iphone 底部安全区 顶部刘海屏(2022-6-29) 

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#165]
[原文地址](https://juejin.cn/post/7031104332422610975)

在 head 标签中添加 meta 标签，并设置 viewport-fit=cover 值

开启顶部适配
```css
/*在这里插入代码片*/
.safe-area-inset-top{
	padding-top: constant(safe-area-inset-top);
 	padding-top: env(safe-area-inset-top);
}
```

开启底部适配
```css
/*在这里插入代码片*/
.safe-area-inset-bottom{
	padding-bottom: constant(safe-area-inset-bottom);
	padding-bottom: env(safe-area-inset-bottom);
}

```
