### ISSUE TITLE
css中一行省略和两行省略

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#18]
## css中一行省略和两行省略  
```css 
.ellipsis {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.two-ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```
