### ISSUE TITLE
用docker 快速搭建一个redis 服务 (2023-05-24)

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#188]
新建一个 `docker-compose.yml`

```yml
version: '3.7'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis-server'
    command: redis-server --requirepass 你的密码
    ports:
      - '6379:6379'
```

执行
```bash
docker-compose up -d
```
