### ISSUE TITLE
学习Grid布局

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#27]
## gird的基本概念  
gird 布局，可以将任意组合不同的网格，做出各种各样的布局。同时呢，gird和flex有一定的相似性，都可以指定容器的多个项目的位置。

### gird 和 flex的重大区别，
`flex`布局是轴线布局，只能指定项目针对轴线的位置，建议看作是一维布局。`grid`布局则是将容器划分为行和列，产生单元格，然后指定项目所在的单元格，可以看做是二维布局。grid布局远比flex布局强大。

### 弄懂什么是容器和项目 
- 采用网格布局的区域，称之为容器 
- 容器内部采用网格定位的子元素，称之为项目

```html
  <div>
        <div>
            <p>1</p>
        </div>
        <div>
            <p>1</p>
        </div>
        <div>
            <p>2</p>
        </div>
    </div>
```
上面的代码中呢，最外层div是元素就是容器，内层的三个div是元素就是项目 
**注意** 项目只能是容器的顶层子元素，不包含项目的子元素，如p元素就不是项目。Grid只是针对项目生效。

**Comment by yaogengzhu** [comment]
### 认识什么是行和列 
 - 容器中，水平区域称之为行（row), 垂直区域称之为列（column）

### 认识单元格 
行和列交叉区域，称之为单元格（cell）
一般情况下，n行和m列会产生nxm个单元格。

### 认识网格线  
划分网格的线，我们称之为网格线。
一般情况下，n行有n+1个水平线，m列有m+1根垂直线

**Comment by yaogengzhu** [comment]
### 认识容器的属性 
Grid布局的属性分成两类。
- 一类定义在容器的上面，称之为容器属性。

**Comment by yaogengzhu** [comment]
## 简单的示范代码 
```httml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .box {
            box-sizing: border-box;
            width: 300px;
            height: 300px;
            border: 1px solid red;
            /* display: inline-grid; */
            /* display: -moz-inline-grid; */
            /* display: inline-grid; */
            display: grid;
            grid-template-columns: 100px 100px 100px;
            grid-template-rows: 100px 100px 100px;
        }

        .box > div:nth-of-type(2n) {
            width: 100px;
            height: 100px;
            background-color: pink;
        }
        .box > div:nth-of-type(2n + 1) {
            width: 100px;
            height: 100px;
            background-color: green;
        }
    </style>
</head>

<body>
    <div class="box">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</body>

</html>
```

**Comment by yaogengzhu** [comment]
### 值得注意的是，除了上面的使用确定的值之外，还可以使用百分比的方式
```css
div { 
      display: grid;
       grid-template-columns: 33.333%  33.333%  33.333%;
       grid-template-rows: 33.33% 33.33% 33.33%;
}
```
是不是发现每次都这样写，非常的累。我也觉得------福利来了，我们可以这样写；

```css
div {
   display: grid;
   grid-template-columns: repeat(3, 33.33%)
   grid-template-rows: repeat(3, 33.33%)
}
```

### 需要记住 repeat() 接收两个参数，`重复的次数`和`重复的值`。

**Comment by yaogengzhu** [comment]
### 继续认识容器的属性和值 

#### 除了认识repeat之外，我们需要知道`auto-fill`关键字。
- 有时候，单元格的大小是固定的，但是容器的大小是不确定的。如果希望每一行或者说每一列都尽量容纳更多的单元格，这个时候我们可以使用`auto-fill`来自动的填充。

```css
.container {
  display: grid;
  grid-template-columns: repeat(auto-fill, 100px);
}
```
表示每列宽度为100， 然后自动填充，直到容器不能放置更多的列。

#### 认识fr关键字 
为了很方便的表示比例关系，网格布局提供列fr关键字（fraction）意思为片段。如果两列的宽度为1fr和2fr,就表示后者是前者的两倍。
```css 
.container {
  display: grid;
  grid-template-columns: 1fr 3fr;
}
```
表示后面一列的宽度是前面一列宽度的3倍；
同时呢，fr可以结合绝对长度的单位一起使用，这样非常的方便。
```css
   display: grid;
   grid-template-columns:  100px 3fr 3fr;
   grid-template-rows: 1fr 2fr;
```
