### ISSUE TITLE
简单的说说position：sticky

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#29]
## 如何使用position:sticky 
用一个简单的导航说吧！！
```css
nav {
     position: -webkit-sticky;
     position: sticky;
     top:0;
  }
```

这个属性的的效果，就像`position:fixed`一样。值得注意的是，要想`position: sticky`生效，top属或者left属性必须要有明确的计算的值，否则fixed的表现不会出现。

当然，这个仅仅是最基础的表现了，今天我用到的地方就是表格区域，用于处理表头！

### 简单的记住一个我不直到的`position: sticky`
这个属性有一个重要的特性，那就是`sticky`元素效果完全受制于父级元素。

这个和`position:fixed`定位有着本质的不同，fixed元素会直抵页面的根元素，其父元素对其left/top，定位都是没有办法限制的。

### sticky表现出来的一些特性。
- 父级元素不能有任何`overflowe: visible`以外的的设置属性，否则就没有粘滞的效果。因为改变了滚动容器（即便是没有出现滚动条。
- 父级元素也不能设置`固定的height值`,否则也没有粘滞的效果。
- 同一个父容器的中的sticky元素，如果定位值相等，则会重叠；如果是不同的父级元素，则会挤开原来的元素，依次形成占位的效果 
- sticky定位，不仅可以设置 top，还可以设置bottom，相对于底部定位，当然，如归是水平滚动，也可以设置`left`和`right`
