### ISSUE TITLE
css中的calc属性（2019-08-19）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#39]
## 认识css 中的calc()  
`calc()` 这个是css函数，可以在声明css属性值时执行一些计算

### 用法
```css
width：calc(100% - 80px）;
```
这个不仅有减法，还有加法，乘法， 除法。

这个适用于在项目中的一些自适应的布局，我一般都是采取flex布局，如果不用的话，用这个还是不错的。 
建议参考 [点我](https://developer.mozilla.org/zh-CN/docs/Web/CSS/calc#%E4%BE%8B%E5%AD%90)

**Comment by yaogengzhu** [comment]
用法还是不错的，举个简单的例子

```html
<div class='box'>
  <div class='box1'></div>
</div>
```
```css
.box {
  width:300px;
  height: 200px;
  background-color:red;
}

.box1 {
  margin:20px auto;
  width:calc(100% - 40px);
  height: 100px;
  background-color: pink;
}
```
