### ISSUE TITLE
grid布局 （2019-10-07）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#59]
### grid 布局 
```css
 .goods-number_box {
            display: grid;
            justify-content: space-between;
            grid-template-columns: repeat(auto-fill, 36px);
            grid-gap: 14px;
            &::after{
                content: '';
                width: 36px;
             }
            .number-list {
                display: inline-block;
                width: 36px;
                height: 36px;
                font-size: 14px;
                text-align: center;
                line-height: 36px;
                color: #333;
                border-radius: 4px;
                background-color: #f7f7f7;
            }
```
