### ISSUE TITLE
CSS 多行省略失效 (-webkit-box-orient 失效) (2019-10-08)

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#60]
### CSS 多行省略失效 (-webkit-box-orient 失效)
```css
.line-ellipsis-2{
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
 /* autoprefixer: off */
  -webkit-box-orient: vertical;
  /* autoprefixer: on */
}
```
