### ISSUE TITLE
IOS下 input输入框不能输入内容(2019-11-28)

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#72]
###  IOS下 input输入框不能输入内容 
>  这个属性差点搞死人哦， 设置了* 之后，ios所有的input框内容都不能输入～  去掉就好了哦

```css
* {
  box-sizing: border-box;
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
input {
    -moz-user-select: text!important;
    -webkit-user-select: text!important;
    -ms-user-select: text!important;
    user-select: text!important;  
}

```
