### ISSUE TITLE
react 页面滚动穿透如何解决（2019-12-14）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#78]
## react 页面滚动穿透如何解决
>  如何理解这个问题呢 ！比较坑吧，对于vue 来说很好处理，给touchMove 直接处理就完事了
```js
<div  onClick={ (e) => { e.stopPropagation(); this.close()}} onTouchMove={(e) => {e.preventDefault()}} id='poperBox'>
</div>
```
> 对于chrome浏览器会报错，那么给css处理下
```css
#poperBox {
    touch-action: none;
}
```
