### ISSUE TITLE
ios对position: sticky的兼容（2019-12-18）

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#81]
### ios 下， 对position: sticky有兼容性
>  当然，iOS下的兼容性挺多的，这个属性对于低版本的iOS有兼容问题， 高版本无问题。
```css
div {
     position: sticky;
     top: 0;
}
```
