### ISSUE TITLE
在tarojs中如何才能拿到根元素操作dom呢？

### ISSUE THREAD

**Issue by yaogengzhu** [yaogengzhu/life-share#88]
## 如何拿到根元素操作dom呢？
- bug 是小程序，opacity:0 在真机上会失效。。
> 有一个密码输入框的需求，需要做自定义的密码输入框，但是需要使用到input 框去聚焦和失去焦点来处理

### 解决方案，
> 通过input 的focus 的true和false来处理，效果不是很理想。

**Comment by yaogengzhu** [comment]
## 通过以 以下方案解决
```css
 .inputBox {
                        position: absolute;
                        width: 100%;
                        top: 0;
                        left: -100%;
                        height: 40px;
                        padding-right: 100%;
                        opacity: 0;
                    }
```
